ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: ./bundled/main.js
    spawn: false
inputs_def:
  - handle: mediaPath
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: mediaInfo
    description: Input
    json_schema:
      type: object
      additionalProperties: false
      properties:
        format_name:
          type: string
        audioChannels:
          type: string
        codeRate:
          type: string
        codecs:
          type: string
        colorProfile:
          type: string
        duration:
          type: string
        name:
          type: string
        kind:
          type: string
        size:
          type: string
        quality:
          type: string
        dimensions:
          type: string
  - handle: outputDir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: isCompress
    json_schema:
      type: boolean
  - handle: targetFormat
    json_schema:
      ui:widget: self::targetFormat
      ui:options:
        title: TargetFormat
    value:
      name: MP4
      value: .mp4
outputs_def:
  - handle: media
    description: Output
    json_schema:
      type: string
icon: ":carbon:video-player:"
