ui:
  default_width: 450
inputs_def:
  - handle: outputDir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: mediaInfo
    description: Output
    json_schema:
      type: object
      additionalProperties: false
      properties:
        path:
          type: string
        dimensions:
          type: object
          additionalProperties: false
          properties:
            height:
              type: number
            width:
              type: number
        size:
          type: number
        containerFormat:
          type: string
        videoCodec:
          type: string
        audioCodec:
          type: string
outputs_def:
  - handle: mediaPath
    description: Output
    json_schema:
      type: string
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: convert-to-mp4
icon: ":carbon:mp4:#519ABA:"
